# Generated by Django 5.0 on 2025-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_title_0e1e41_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_locatio_8b2f8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_remote__161327_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_visa_sp_1416c6_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AlterField(
            model_name='job',
            name='remote_type',
            field=models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=6),
        ),
        migrations.AlterField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False),
        ),
    ]
