# Generated by Django 5.0 on 2025-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
