# Generated by Django 5.0 on 2025-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
