# Generated by Django 5.0 on 2025-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(db_index=True, default='Unknown', max_length=200),
        ),
    ]
