# Generated by Django 5.0 on 2025-10-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('CLOSED', 'Closed')], default='APPLIED', max_length=20),
        ),
    ]
