# Generated by Django 5.0 on 2025-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_min_experience'),
        ('jobs', '0006_alter_application_status'),
    ]

    operations = [
    ]
