# Generated by Django 5.0 on 2025-10-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_address'),
        ('jobs', '0007_merge_20251021_1327'),
    ]

    operations = [
    ]
