# Generated by Django 5.0 on 2025-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_merge_0004_job_address_0007_merge_20251021_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
