# Generated by Django 5.0 on 2025-09-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0003_remove_jobseeker_skills_jobseeker_skills'),
        ('jobSeekers', '0004_jobseeker_hide_location'),
    ]

    operations = [
    ]
