# Generated by Django 5.0 on 2025-09-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('startDate', models.CharField(max_length=7, verbose_name='Start Date (mm/yyyy)')),
                ('endDate', models.CharField(blank=True, max_length=7, verbose_name='End Date (mm/yyyy)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobSeeker_images/', verbose_name='Profile Image')),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('startYear', models.IntegerField(blank=True, null=True, verbose_name='Start Year')),
                ('endYear', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('headline', models.TextField(blank=True)),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobSeekers', to='jobSeekers.institution')),
                ('experience', models.ManyToManyField(blank=True, related_name='jobSeekers', to='jobSeekers.experience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='jobSeekers', to='jobSeekers.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('jobSeeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='jobSeekers.jobseeker')),
            ],
        ),
    ]
