# Generated by Django 5.0 on 2025-09-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('profileImage', models.ImageField(upload_to='jobseeker_images/')),
                ('degree', models.TextField()),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
                ('headline', models.TextField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobSeekers.institution')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='jobSeeker',
            field=models.ManyToManyField(to='jobSeekers.jobseekerprofile'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('jobSeeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobSeekers.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('jobSeeker', models.ManyToManyField(to='jobSeekers.jobseekerprofile')),
            ],
        ),
    ]
