# Generated by Django 5.0 on 2025-09-23 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='jobSeeker',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='jobSeeker',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='job_seekers', to='jobSeekers.skill'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='jobSeekers.institution'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
