# Generated by Django 5.0 on 2025-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0002_jobseeker_hide_headline_jobseeker_hide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='hide_profile',
            field=models.BooleanField(default=False),
        ),
    ]
