# Generated by Django 5.0 on 2025-09-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0002_alter_jobseeker_degree_alter_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
