# Generated by Django 5.0 on 2025-09-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0002_rename_name_skill_skill_remove_institution_jobseeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='endYear',
            field=models.IntegerField(verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='firstName',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='lastName',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profileImage',
            field=models.ImageField(upload_to='jobseeker_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='startYear',
            field=models.IntegerField(verbose_name='Start Year'),
        ),
    ]
