# Generated by Django 5.0 on 2025-09-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0003_alter_jobseekerprofile_endyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobSeeker_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_seekers', to='jobSeekers.institution'),
        ),
    ]
