# Generated by Django 5.0 on 2025-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0003_jobseeker_hide_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='hide_location',
            field=models.BooleanField(default=False),
        ),
    ]
