# Generated by Django 5.0 on 2025-09-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0004_remove_jobseekerprofile_profileimage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeekerProfile',
            new_name='JobSeeker',
        ),
    ]
