# Generated by Django 5.0 on 2025-09-25 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0005_rename_jobseekerprofile_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('startDate', models.CharField(max_length=10)),
                ('endDate', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobSeeker', to='jobSeekers.institution'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='endYear',
            field=models.IntegerField(blank=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(related_name='jobSeeker', to='jobSeekers.skill'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.ManyToManyField(related_name='jobSeeker', to='jobSeekers.experience'),
        ),
    ]
