# Generated by Django 5.0 on 2025-09-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0005_merge_20250926_1856'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobSeekers', to='jobSeekers.institution'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='endYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='firstName',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobSeeker_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='lastName',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='startYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Year'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='jobSeekers', to='jobSeekers.experience'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobSeekers', to='jobSeekers.skill'),
        ),
    ]
