# Generated by Django 5.0 on 2025-09-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0006_alter_jobseeker_degree_alter_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='jobSeeker',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='jobSeeker', to='jobSeekers.link'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobSeeker', to='jobSeekers.institution'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='jobSeeker', to='jobSeekers.experience'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobSeeker', to='jobSeekers.skill'),
        ),
    ]
