# Generated by Django 5.0 on 2025-09-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0006_experience_alter_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.CharField(blank=True, max_length=7, verbose_name='End Date (mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.CharField(max_length=7, verbose_name='Start Date (mm/yyyy)'),
        ),
    ]
