# Generated by Django 5.0 on 2025-09-25 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0007_alter_experience_enddate_alter_experience_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Company'),
            preserve_default=False,
        ),
    ]
