# Generated by Django 5.0 on 2025-10-06 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0007_remove_link_jobseeker_jobseeker_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameHeadline', models.CharField(max_length=255, verbose_name='Name or Headline')),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('matches', models.ManyToManyField(blank=True, related_name='matched_searches', to='jobSeekers.jobseeker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
