# Generated by Django 5.0 on 2025-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0007_remove_link_jobseeker_jobseeker_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='desired_salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='desired_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='open_to_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
