# Generated by Django 5.0 on 2025-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0008_jobseeker_desired_salary_max_and_more'),
        ('jobSeekers', '0009_notification'),
    ]

    operations = [
    ]
