# Generated by Django 5.0 on 2025-11-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekers', '0010_merge_20251021_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_radius_miles',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
