# Generated by Django 5.0 on 2025-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='weight_experience',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='weight_location',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='weight_skill',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
