# Generated by Django 5.0 on 2025-10-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruiterprofile_weight_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='experience_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='skill_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6),
        ),
    ]
