# Generated by Django 5.0 on 2025-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amount_left',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
